### PR TITLE
 Add compatibility with speical licenses and fix the taskbar issue #2 

### LINKED ISSUE #1: Doesn't work after the July 2025 update
It seems to launch fine, but only in exclusive fullscreen mode.

The game got an update on July this year, adding Cloud support and Steam Deck compatibility.

### PR DESCRIPTION
**Pull request by klaritan**
Fixes all discovered issues from here: https://github.com/ColleagueRiley/lego-batman-borderless-fullscreen-hack/issues/1

Previous pull request was closed as it had a sizing issue. This fixes that issue as well.

### CODE REVIEW

File: hook.c [hunk 1]
```diff
@@ -36,12 +47,15 @@ DWORD hook(LPVOID lpThreadParameter) {
     monitorInfo.cbSize = sizeof(MONITORINFOEX);
     GetMonitorInfoA(src, (LPMONITORINFO)&monitorInfo);
 
-    UINT width  = monitorInfo.rcWork.right - monitorInfo.rcWork.left;
-    UINT height = monitorInfo.rcWork.bottom - monitorInfo.rcWork.top;
+    UINT width  = monitorInfo.rcMonitor.right - monitorInfo.rcMonitor.left;
```
Comment (ColleagueRiley) [inline hook.c:50]: IIrc this mistake was inherited from RGFW. I fixed it there but not here

File: hook.c [hunk 2]
```diff
@@ -36,12 +47,15 @@ DWORD hook(LPVOID lpThreadParameter) {
     monitorInfo.cbSize = sizeof(MONITORINFOEX);
     GetMonitorInfoA(src, (LPMONITORINFO)&monitorInfo);
 
-    UINT width  = monitorInfo.rcWork.right - monitorInfo.rcWork.left;
-    UINT height = monitorInfo.rcWork.bottom - monitorInfo.rcWork.top;
+    UINT width  = monitorInfo.rcMonitor.right - monitorInfo.rcMonitor.left;
+    UINT height = monitorInfo.rcMonitor.bottom - monitorInfo.rcMonitor.top;
+
+    LONG lStyle = GetWindowLong(hWnd, GWL_STYLE);
+    lStyle &= ~(WS_CAPTION | WS_THICKFRAME | WS_MINIMIZEBOX | WS_MAXIMIZEBOX | WS_SYSMENU);
```
Comment (ColleagueRiley) [inline hook.c:54]: looks good

File: hook.c [hunk 3]
```diff
@@ -1,6 +1,17 @@
 #include <windows.h>
 #include <stdio.h>
 
+int strEndsWith(const char *str, const char *suffix) {
+    if (!str || !suffix)
```
Comment (ColleagueRiley) [inline hook.c:5]: I would prefer == NULL, but this is fine.

It's not really required however considering we KNOW str == `char title[256]` and sufix == "Batman" 

so this statement will never be true.

File: hook.c [hunk 4]
```diff
@@ -11,7 +22,7 @@ BOOL CALLBACK checkWindow(HWND hWnd, LPARAM lParam) {
     char title[256];
     GetWindowTextA(hWnd, title, sizeof(title));
 
-    if (strstr(title, "LEGO") && strstr(title, "Batman") && strlen(title) == 13) {
+    if (strstr(title, "LEGO") && strEndsWith(title, "Batman")) {
```
Comment (ColleagueRiley) [inline hook.c:25]: I'm pretty sure my version ends with the reserved symbol, so I'm not sure if this is going to work

File: hook.c [hunk 5]
```diff
@@ -1,6 +1,17 @@
 #include <windows.h>
 #include <stdio.h>
 
+int strEndsWith(const char *str, const char *suffix) {
+    if (!str || !suffix)
+        return 0;
+    size_t lenstr = strlen(str);
```
Comment (ColleagueRiley) [inline hook.c:7]: Imo the use of `strlen` should be replaced considering we know the size of both.

I believe this is a problem originating from my original code. `GetWindowTextA` returns the length of the title and we can easily do
```c
const char substr[] = "Batman";
sizeof(substr); // the length 
```

**Comment by ColleagueRiley** [comment]
I added some comments of things I would like changed. You don't have to change them, I can change it later on if you don't.

I will test this on my system, but I'm not 100% sure if this is going to work considering it checks for "Batman" at the end of the title, but in my version the end of the title has the reserved logo.

**Comment by ColleagueRiley** [comment]
In case you're wording 
```c
strstr(title, "LEGO") && strstr(title, "Batman") 
```
Doesn't work because if, for example, you search "LEGO Batman" on your web browser, that window will be selected.

**Comment by ColleagueRiley** [comment]
Thanks for the help tracking down the cause of the issue and for the PR
